[package]
name = "img-parts"
version = "0.1.1" # remember to update html_root_url and README.md
authors = ["Paolo Barbolini <paolo@paolo565.org>"]
description = "Low level crate for reading and writing Jpeg, Png and RIFF image containers"
license = "MIT/Apache-2.0"
repository = "https://github.com/paolobarbolini/img-parts"
categories = ["multimedia::images", "multimedia::encoding", "parser-implementations"]
keywords = ["jpeg", "png", "parser", "icc", "exif"]
readme = "README.md"
edition = "2018"

exclude = [
    "tests/",
]

[dependencies]
bytes = "0.5.3"
crc32fast = "1.1.1"
miniz_oxide = "0.4"

[package.metadata.docs.rs]
targets = []
